const {test}=require('node:test');
const assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function app(){const dom=new JSDOM('<div id="mainWrap"><div id="contextNav"></div><div id="flash"></div><main id="app"></main></div><nav id="nav"></nav>',{url:'https://core.test',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,run=s=>vm.runInContext(s,dom.getInternalVMContext());const calls=[],requests=[];let handler=async p=>p.includes('/meta')?{}:p==='/api/dashboard/badges'?{}:[];
w.matchMedia=()=>({matches:false});w.confirm=()=>true;w.fetch=async(p,o)=>{calls.push(p);requests.push({path:p,options:o});return {ok:true,json:async()=>handler(p)}};
for(const f of ['cache','app','directories']){let source=fs.readFileSync(path.join(__dirname,`../miniapp/${f}.1.7.15.js`),'utf8');if(f==='app')source=source.slice(0,source.lastIndexOf('auth().catch'));run(source);}
run("state.token='test';state.user={role:'admin',full_name:'Test'};renderNav();");return {w,run,calls,requests,handler:f=>handler=f,close:()=>w.close()};}
const tick=()=>new Promise(r=>setImmediate(r));
test('warmed employees/tasks/knowledge navigate without foreground HTTP',async()=>{const a=app();try{for(const page of ['employees','tasks','knowledge']){await a.run(`go('${page}')`);await tick();const before=a.calls.length;await a.run(`go('${page}')`);await tick();assert.equal(a.calls.length,before,page);assert.equal(a.w.document.querySelector('.screen-skeleton'),null);assert.ok(!a.w.document.getElementById('app').textContent.includes('undefined'));}}finally{a.close();}});
test('task metadata and rows start in parallel',async()=>{const a=app();try{const release=[];a.handler(p=>p.startsWith('/api/tasks-v2')?new Promise(r=>release.push(()=>r(p.endsWith('/meta')?{}:[]))):{});const job=a.run("go('tasks')");await tick();assert.equal(release.length,2);release.forEach(r=>r());await job;}finally{a.close();}});
test('late previous section response cannot overwrite newer section',async()=>{const a=app();try{const release=[];a.handler(p=>p.startsWith('/api/employees')?new Promise(r=>release.push(()=>r(p.endsWith('/meta')?{}:[]))):p==='/api/dashboard/badges'?{}:[]);const old=a.run("go('employees')");await tick();await a.run("go('knowledge')");const expected=a.w.document.getElementById('app').innerHTML;release.forEach(r=>r());await old;assert.equal(a.w.document.getElementById('app').innerHTML,expected);assert.equal(a.run('state.page'),'knowledge');}finally{a.close();}});
test('stale cached screen opens while slow revalidation runs',async()=>{const a=app();try{await a.run("go('employees')");await tick();a.run('dataCache.now=()=>Date.now()+45000');let pending=0;a.handler(p=>p.startsWith('/api/employees')?new Promise(()=>pending++):{});let complete=false;a.run("go('employees')").then(()=>complete=true);await tick();assert.equal(complete,true);assert.equal(pending,2);assert.equal(a.w.document.querySelector('.screen-skeleton'),null);}finally{a.close();}});
test('preloading does not render another screen or change navigation',async()=>{const a=app();try{await a.run("go('knowledge')");const expected=a.w.document.getElementById('app').innerHTML;a.run("queueScreenWarmup('employees')");await new Promise(r=>setTimeout(r,260));assert.equal(a.w.document.getElementById('app').innerHTML,expected);assert.equal(a.run('state.page'),'knowledge');assert.ok(a.calls.includes('/api/employees/meta'));}finally{a.close();}});

test('directory screen keeps BIGINT IDs and requires explicit mapping selection',async()=>{const a=app();try{const id='90071992547409931234';const d={configured:true,status:'success',snapshot:{store_count:0,seller_count:1,stores:[],sellers:[{saby_seller_id:id,display_name:'<img src=x onerror=alert(1)>',observed_names:[],stores:[]}]},stores:[],employees:[{id:7,name:'Employee',active:true}],links:[]};a.handler(async p=>p==='/api/admin-center/saby'?d:{});await a.run("state.page='admin';state.adminTab='saby';sabyKind='seller';renderSabyDirectories()");assert.equal(a.w.document.querySelector('#sabyRows img'),null);assert.equal(a.w.document.getElementById('sabyTarget0').value,'');a.w.document.getElementById('sabyTarget0').value='7';await a.run('saveSabyLink(0)');const req=a.requests.find(r=>r.path.endsWith('/saby/link'));const payload=JSON.parse(req.options.body);assert.equal(payload.saby_id,id);assert.equal(payload.core_id,7);assert.equal(payload.expected_revision,0);}finally{a.close();}});
