/* Admin-only mapping of observed Saby payment accounts to existing Core records. */
let sabyView=null,sabyKind='store',sabyFilter='all',sabyQuery='',sabyRows=[];
function sabyStamp(v){return v?new Date(/[zZ]|[+-]\d\d:\d\d$/.test(v)?v:v+'Z').toLocaleString('ru-RU'):'Нет данных';}
function sabyNormal(v){return String(v||'').toLocaleLowerCase('ru-RU').replace(/ё/g,'е').replace(/[^а-яa-z0-9]/g,'');}
async function renderSabyDirectories(){
 try{const d=await api('/api/admin-center/saby');if(state.page!=='admin'||state.adminTab!=='saby')return;sabyView=d;paintSabyDirectories();}
 catch(e){if(e?.name!=='AbortError'&&state.page==='admin'&&state.adminTab==='saby')adminFrame('saby',`<div class="notice error">${esc(e.message)}</div>`);}
}
function paintSabyDirectories(){
 const d=sabyView,s=d.snapshot;
 adminFrame('saby',`<div class="card"><div class="row between"><h3>Связь с Saby</h3><button class="btn mini" id="sabySync" onclick="syncSabyDirectories()" ${!d.configured||d.status==='running'?'disabled':''}>${d.status==='running'?'Загрузка выполняется…':'Загрузить из Причал AI'}</button></div><div class="small">Получено в Core: ${esc(sabyStamp(d.imported_at))}<br>Последняя попытка: ${esc(sabyStamp(d.attempted_at))}<br>Загрузка данных в AI: ${esc(sabyStamp(s?.last_successful_sync_at))}</div>${d.config_error?`<div class="notice error">${esc(d.config_error)}</div>`:''}${d.error?`<div class="notice error">${esc(d.error)}</div>`:''}${d.status==='running'?'<button class="btn secondary mini" onclick="renderSabyDirectories()">Проверить результат</button>':''}</div><div class="notice">Продавцы здесь — учётки из продаж, не кадровый справочник. Совпадение имени требует подтверждения. Даты и магазины показывают наблюдения в загруженных продажах, а не приём, увольнение или закрепление сотрудника.</div>${!s?'<div class="notice">Справочники ещё не загружены. Нажмите «Загрузить из Причал AI».</div>':`<div class="row"><button class="btn ${sabyKind==='store'?'':'secondary'}" onclick="sabyKind='store';paintSabyDirectories()">Магазины (${s.store_count})</button><button class="btn ${sabyKind==='seller'?'':'secondary'}" onclick="sabyKind='seller';paintSabyDirectories()">Учётки (${s.seller_count})</button></div><div class="card">${field('Поиск',`<input id="sabySearch" value="${esc(sabyQuery)}" placeholder="Имя, название или ID" oninput="sabyQuery=this.value;paintSabyRows()">`)}${field('Показать',`<select onchange="sabyFilter=this.value;paintSabyRows()"><option value="all" ${sabyFilter==='all'?'selected':''}>Все</option><option value="unlinked" ${sabyFilter==='unlinked'?'selected':''}>Без связи</option><option value="linked" ${sabyFilter==='linked'?'selected':''}>Связанные</option><option value="missing" ${sabyFilter==='missing'?'selected':''}>Нет в последней выгрузке</option></select>`)}</div><div id="sabyRows"></div><div id="sabyLocalOnly"></div>`}`);
 if(s)paintSabyRows();
}
function paintSabyRows(){
 const d=sabyView,s=d.snapshot,store=sabyKind==='store',key=store?'saby_point_id':'saby_seller_id',local=store?d.stores:d.employees;
 const links=new Map(d.links.filter(l=>l.kind===sabyKind).map(l=>[l.saby_id,l]));
 sabyRows=(store?s.stores:s.sellers).map(r=>({...r,id:r[key],label:store?r.name:r.display_name,link:links.get(r[key]),missing:false}));
 const present=new Set(sabyRows.map(r=>r.id));for(const l of links.values())if(!present.has(l.saby_id))sabyRows.push({id:l.saby_id,label:l.label,link:l,missing:true});
 const options=(r)=>{const current=r.link?.core_id;return '<option value="">Не связывать</option>'+(!store?`<option value="shared" ${r.link?.shared?'selected':''}>Общая учётка — без личной привязки</option>`:'')+local.filter(x=>x.active||x.id===current).map(x=>`<option value="${x.id}" ${x.id===current?'selected':''}>${esc(x.name)} · #${x.id}${!x.active?' (неактивен)':''}</option>`).join('');};
 document.getElementById('sabyRows').innerHTML=sabyRows.map((r,i)=>{
 const linked=!!(r.link?.core_id||r.link?.shared),name=local.find(x=>x.id===r.link?.core_id)?.name||'';
 if(sabyFilter==='unlinked'&&linked||sabyFilter==='linked'&&!linked||sabyFilter==='missing'&&!r.missing)return '';
 if(sabyQuery&&!sabyNormal([r.id,r.label,name,...(r.observed_names||[])].join(' ')).includes(sabyNormal(sabyQuery)))return '';
 const same=!linked&&!r.missing?local.filter(x=>x.active&&sabyNormal(x.name)&&[r.label,...(r.observed_names||[])].some(n=>sabyNormal(n)===sabyNormal(x.name))):[];
 const locations=(r.stores||[]).map(x=>s.stores.find(p=>p.saby_point_id===x.saby_point_id)?.name||x.saby_point_id);
 return `<div class="card"><div class="row between"><b>${esc(r.label||'Без имени')}</b><span class="pill">${r.missing?'Нет в последней выгрузке':r.link?.shared?'Общая учётка':linked?'Связано':'Без связи'}</span></div><div class="small">Saby ID: ${esc(r.id)}</div>${store?`<div class="small">${esc(r.address||'')}</div>`:`<div class="small">Варианты имени: ${esc((r.observed_names||[]).join(' / ')||'—')}<br>Наблюдалась: ${esc(r.first_seen||'—')} — ${esc(r.last_seen||'—')}<br>Магазины в продажах: ${esc(locations.join(', ')||'—')}</div>`}${same.length?`<div class="notice">Совпадает имя: ${esc(same.map(x=>x.name+' (#'+x.id+')').join(', '))}. Проверьте и выберите запись ниже.</div>`:''}${r.missing?`<div class="small">Сохранённая связь: ${esc(name|| (r.link?.shared?'Общая учётка':'Нет'))}. Отсутствие в выгрузке не означает увольнение или закрытие.</div><button class="btn secondary mini" onclick="saveSabyLink(${i},true)">Снять связь</button>`:`${field(store?'Магазин Core':'Сотрудник Core',`<select id="sabyTarget${i}">${options(r)}</select>`)}<button class="btn mini" onclick="saveSabyLink(${i})">Подтвердить связь</button>`}</div>`;
 }).join('')||'<div class="notice">Нет записей по выбранному фильтру.</div>';
 const used=new Set(d.links.filter(l=>l.kind===sabyKind&&l.core_id).map(l=>l.core_id));const only=local.filter(x=>x.active&&!used.has(x.id));
 document.getElementById('sabyLocalOnly').innerHTML=`<div class="card"><h3>Без связи в Core (${only.length})</h3><div class="small">${esc(only.map(x=>x.name).join(' · ')||'Все связаны')}${!store?'<br>Ночные помощники и другие сотрудники без учётки Saby могут оставаться без связи.':''}</div></div>`;
}
async function syncSabyDirectories(){const b=document.getElementById('sabySync');b.disabled=true;b.textContent='Загружаю…';try{const d=await api('/api/admin-center/saby/sync',{method:'POST',body:'{}'});flash(`Получено магазинов: ${d.store_count}, учёток: ${d.seller_count}`);}catch(e){flash(e.message,'error');}finally{if(state.page==='admin'&&state.adminTab==='saby')await renderSabyDirectories();}}
async function saveSabyLink(i,remove=false){const r=sabyRows[i],kind=sabyKind,value=remove?'':document.getElementById('sabyTarget'+i).value,shared=value==='shared',coreId=value&&!shared?Number(value):null;const target=(kind==='store'?sabyView.stores:sabyView.employees).find(x=>x.id===coreId);if(!confirm(`${coreId?'Связать с «'+target.name+'»':shared?'Отметить как общую учётку':'Снять связь'} для Saby «${r.label||r.id}»?`))return;try{await api('/api/admin-center/saby/link',{method:'PUT',body:JSON.stringify({kind,saby_id:r.id,core_id:coreId,shared,expected_revision:r.link?.revision||0})});flash('Связь сохранена');if(state.page==='admin'&&state.adminTab==='saby')await renderSabyDirectories();}catch(e){flash(e.message,'error');}}
